import test from 'node:test';
import assert from 'node:assert/strict';
import fsp from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {startBackupFromManifest} from '../src/core/backup.mjs';
import {startRestoreFromManifest} from '../src/core/restore.mjs';
import {renderTemplate} from '../src/core/template.mjs';
import {executeWorkflow} from '../src/core/workflow.mjs';
const S='workspace-recover/';
const gnu=()=>({schema:S+'archive-profile/v3',kind:'exec',format:'tar.gz',requires:{executables:['tar']},pack:{argv:['tar','--format=pax','--hard-dereference','--null','--verbatim-files-from','--no-recursion','-C','${sourceRoot}','-czf','${archivePath}','-T','${selectionNul}']},unpack:{argv:['tar','-xzf','${archivePath}','--no-same-owner','--same-permissions','--delay-directory-restore','-C','${targetRoot}']}});
async function setup(t){const root=await fsp.mkdtemp(path.join(os.tmpdir(),'wr-codec-'));t.after(()=>fsp.rm(root,{recursive:true,force:true}));const source=path.join(root,'source space');await fsp.mkdir(source);for(const name of ['a.txt','dir/b.txt','dir/skip.log','line\nbreak.txt','--option','д'.repeat(60)+'.txt']){await fsp.mkdir(path.dirname(path.join(source,name)),{recursive:true});await fsp.writeFile(path.join(source,name),name);}return{root,source,manifest:{schema:S+'manifest/v3',name:'codec-test',backup:{source:{path:source,include:['**'],exclude:['**/*.log']},provider:{type:'local-files',root:path.join(root,'remote')}},restore:{workflow:[]},handoff:{provider:{type:'local-files',root:path.join(root,'remote')},subject:'rebranding'}}};}
async function backup(f,profile){f.manifest.archiveProfile=profile;const file=path.join(f.root,'manifest.json');await fsp.writeFile(file,JSON.stringify(f.manifest));return startBackupFromManifest({manifestPath:file,stateRoot:path.join(f.root,'state')});}
async function json(p){return JSON.parse(await fsp.readFile(p));}
test('036: paired GNU commands pack exact NUL selection and ordinary restore uses frozen profile',async t=>{const f=await setup(t),s=await backup(f,gnu());assert.equal(s.state,'completed',JSON.stringify(s));assert.ok(s.info.pack);const recovery=path.join(path.dirname(s.planPath),'workspace-recovery-manifest.json');const r=await json(recovery);assert.equal(r.archiveProfile.kind,'exec');assert.ok(r.requires.features.includes('archive-profiles'));await fsp.rename(f.source,f.source+'.hidden');const out=path.join(f.root,'restore');const x=await startRestoreFromManifest({manifestPath:recovery,target:out,stateRoot:path.join(f.root,'rstate')});assert.equal(x.state,'completed',JSON.stringify(x));assert.ok(x.info.unpack);assert.equal(await fsp.readFile(path.join(out,'line\nbreak.txt'),'utf8'),'line\nbreak.txt');assert.equal(await fsp.stat(path.join(out,'dir/skip.log')).catch(()=>null),null);});
test('036: unknown profile versions and incomplete pairs fail before capture',async t=>{for(const p of [{...gnu(),schema:S+'archive-profile/v2'},{...gnu(),unpack:undefined},{...gnu(),pack:{argv:['node','${typo}']}}]){const f=await setup(t);await assert.rejects(()=>backup(f,p),/profile|unpack|placeholder/i);}});
test('036: nonzero custom pack never falls back to builtin writer',async t=>{const f=await setup(t),p=gnu();p.pack={argv:[process.execPath,'-e','process.exit(19)']};await assert.rejects(()=>backup(f,p),/pack|19|failed/i);});
test('036: zero-exit unpack missing data fails inventory before author verification',async t=>{const f=await setup(t),p=gnu(),marker=path.join(f.root,'tests-ran');p.unpack={argv:[process.execPath,'-e','process.exit(0)']};f.manifest.restore.workflow=[{id:'author-test',type:'verification',argv:[process.execPath,'-e',`require('fs').writeFileSync(${JSON.stringify(marker)},'ran')`]}];await assert.rejects(()=>backup(f,p),/inventory|missing|mode/i);assert.equal(await fsp.stat(marker).catch(()=>null),null);});
test('036: executable requirement is explicit and no network installation attempted',async t=>{const f=await setup(t),p=gnu();p.requires.executables=['workspace-recover-not-a-real-command'];await assert.rejects(()=>backup(f,p),/executable|requirement|not.*found/i);});
test('036: profile placeholders are late bound, not operator input requirements',async()=>{const template={schema:S+'template/v3',inputs:{},manifest:{schema:S+'manifest/v3',archiveProfile:gnu(),backup:{source:{path:'/source'}},restore:{workflow:[]}}};const r=await renderTemplate(template,{});assert.deepEqual(r.missing,[]);assert.equal(r.manifest.archiveProfile.pack.argv[7],'${sourceRoot}');});
test('036: external unpack cannot start through an existing root symlink',async t=>{const f=await setup(t),s=await backup(f,gnu()),manifest=path.join(path.dirname(s.planPath),'workspace-recovery-manifest.json');const r=await json(manifest);r.restore.existingTarget='merge';const outside=path.join(f.root,'outside');await fsp.mkdir(outside);await fsp.writeFile(path.join(outside,'sentinel'),'unchanged');const target=path.join(f.root,'target');await fsp.symlink(outside,target);const edited=path.join(f.root,'edited.json');await fsp.writeFile(edited,JSON.stringify(r));await assert.rejects(()=>startRestoreFromManifest({manifestPath:edited,target,stateRoot:path.join(f.root,'rstate')}),/symlink|target|profile/i);assert.equal(await fsp.readFile(path.join(outside,'sentinel'),'utf8'),'unchanged');});
test('036: standalone decoder bootstrap is transported separately and works after original disappears',async t=>{
  const f=await setup(t),codec=path.join(f.root,'codec.cjs');
  await fsp.writeFile(codec,`const fs=require('fs'),p=require('path');const [op,root,archive,list]=process.argv.slice(2);if(op==='pack'){const names=fs.readFileSync(list,'utf8').split('\\0').filter(Boolean);const entries=names.map(name=>{const file=p.join(root,name),s=fs.lstatSync(file);return {name,mode:s.mode&4095,directory:s.isDirectory(),data:s.isFile()?fs.readFileSync(file).toString('base64'):null};});fs.writeFileSync(archive,JSON.stringify(entries),{flag:'wx'});}else{const entries=JSON.parse(fs.readFileSync(archive));for(const e of entries){const file=p.join(root,e.name);if(e.directory)fs.mkdirSync(file,{recursive:true,mode:448});else{fs.mkdirSync(p.dirname(file),{recursive:true});fs.writeFileSync(file,Buffer.from(e.data,'base64'));fs.chmodSync(file,e.mode);}}for(const e of entries.filter(e=>e.directory).reverse())fs.chmodSync(p.join(root,e.name),e.mode);}`);
  const p={schema:S+'archive-profile/v3',kind:'exec',format:'tree.json',requires:{executables:['node']},bootstrap:[{id:'codec',path:codec}],pack:{argv:['node','${bootstrap.codec}','pack','${sourceRoot}','${archivePath}','${selectionNul}']},unpack:{argv:['node','${bootstrap.codec}','unpack','${targetRoot}','${archivePath}']}};
  const s=await backup(f,p);assert.equal(s.state,'completed',JSON.stringify(s));const manifest=path.join(path.dirname(s.planPath),'workspace-recovery-manifest.json');const r=await json(manifest);assert.ok(r.archiveProfile.bootstrap[0].remote.id);assert.equal(r.archiveProfile.bootstrap[0].path,undefined);
  await fsp.unlink(codec);await fsp.rename(f.source,f.source+'.old');const target=path.join(f.root,'restored');const x=await startRestoreFromManifest({manifestPath:manifest,target,stateRoot:path.join(f.root,'rest-state')});assert.equal(x.state,'completed');assert.equal(await fsp.readFile(path.join(target,'a.txt'),'utf8'),'a.txt');
  await fsp.writeFile(r.archiveProfile.bootstrap[0].remote.id,'tampered');await assert.rejects(()=>startRestoreFromManifest({manifestPath:manifest,target:path.join(f.root,'rejected'),stateRoot:path.join(f.root,'bad-state')}),/bootstrap|mismatch/i);
});
test('036: declared timeout terminates a command ignoring SIGTERM and remains advisory',async t=>{const root=await fsp.mkdtemp(path.join(os.tmpdir(),'wr-timeout-'));t.after(()=>fsp.rm(root,{recursive:true,force:true}));const result=await executeWorkflow({steps:[{id:'timeout',type:'verification',argv:[process.execPath,'-e',"process.on('SIGTERM',()=>{});setInterval(()=>{},1000)"],timeoutMs:150}],workspace:root,sessionDir:path.join(root,'evidence')});assert.equal(result.results[0].timedOut,true);assert.equal(result.results[0].signal,'SIGKILL');assert.equal(result.advisoryWarnings,true);assert.equal(result.hardFailure,false);});
test('036: supplied profile self-version and paired argv are validated before provider calls',async()=>{const {executeRecoveryManifest}=await import('../src/core/restore.mjs');let called=false;const r={schema:S+'recovery-manifest/v3',archiveProfile:{...gnu(),schema:S+'archive-profile/v2'},requires:{formatVersion:3,features:['archive-profiles']},transport:{schema:S+'transport-manifest/v3',archive:{fileName:'x.tar.gz',format:'tar.gz',bytes:1,sha256:'1'.repeat(64)},parts:[{index:0,fileName:'part',bytes:1,sha256:'1'.repeat(64),remote:{id:'x'}}]},restore:{workflow:[]}};await assert.rejects(()=>executeRecoveryManifest({recovery:r,target:'/unused',sessionDir:'/unused',provider:{download(){called=true;}}}),/profile/);assert.equal(called,false);});
