import test from 'node:test';
import assert from 'node:assert/strict';
import fsp from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';
import { startBackupFromManifest } from '../src/core/backup.mjs';
import { startRestore, startRestoreFromManifest, continueRestore } from '../src/core/restore.mjs';
import { SessionStore } from '../src/core/session.mjs';
import { GoogleWorkspaceProvider, googleProfileDir, driveId, gmailMessageId } from '../src/providers/google-workspace.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const cli=path.join(root,'bin/workspace-recover.mjs');
const write=(p,v)=>fsp.writeFile(p,JSON.stringify(v)+'\n');
async function fixture(){const d=await fsp.mkdtemp(path.join(os.tmpdir(),'wr-handoff-'));await fsp.mkdir(path.join(d,'source'));await fsp.writeFile(path.join(d,'source','data'),'preserved');const state=path.join(d,'state'),config=path.join(d,'config');const m=path.join(d,'backup.json');await write(m,{schema:'workspace-recover/manifest/v3',name:'project-demo',backup:{source:{path:path.join(d,'source')},provider:{type:'local-files',root:path.join(d,'objects')}},restore:{workflow:[]},handoff:{provider:{type:'local-files',root:path.join(d,'objects')}}});const s=await startBackupFromManifest({manifestPath:m,stateRoot:state});return {d,state,config,s,manifest:path.join(state,'sessions',s.id,'workspace-recovery-manifest.json')};}
function run(f,...args){return spawnSync(process.execPath,[cli,...args],{cwd:f.d,encoding:'utf8',env:{...process.env,WORKSPACE_RECOVER_STATE_DIR:f.state,WORKSPACE_RECOVER_CONFIG_DIR:f.config}});}
test('032: positional recovery manifest is enough for restore',async()=>{const f=await fixture();const out=run(f,'restore',f.manifest,'--target',path.join(f.d,'out'));assert.equal(out.status,0,out.stderr);assert.equal(await fsp.readFile(path.join(f.d,'out/data'),'utf8'),'preserved');});
test('032: positional local handoff, current context info and full path only',async()=>{const f=await fixture();const out=run(f,'restore',f.s.handoff.url,'--target',path.join(f.d,'out'));assert.equal(out.status,0,out.stderr);const info=run(f,'info','--full');assert.equal(info.status,0,info.stderr);assert.equal(info.stdout.trim().split('\n').length,1);assert.ok((await fsp.stat(info.stdout.trim())).isFile());});
test('032: bundled profile values create local versioned profile and infer target',async()=>{const f=await fixture();const values=path.join(f.d,'values.json');await write(values,{schema:'workspace-recover/values/v3',values:{workspaceRoot:path.join(f.d,'work'),googleProfile:'personal'}});let out=run(f,'profile','create','personal','--values',values);assert.equal(out.status,0,out.stderr);out=run(f,'restore',f.manifest,'--profile','personal');assert.equal(out.status,0,out.stderr);assert.equal(await fsp.readFile(path.join(f.d,'work/project-demo/data'),'utf8'),'preserved');const p=JSON.parse(await fsp.readFile(path.join(f.config,'profiles/personal.json')));assert.equal(p.schema,'workspace-recover/profile/v3');});
test('032: wrong profile format and unsafe profile names are rejected',async()=>{const f=await fixture();await fsp.mkdir(path.join(f.config,'profiles'),{recursive:true});await write(path.join(f.config,'profiles/bad.json'),{schema:'workspace-recover/profile/v1',workspaceRoot:f.d});assert.notEqual(run(f,'restore',f.manifest,'--profile','bad').status,0);assert.throws(()=>googleProfileDir('../credentials'),/profile/);});
test('032: unsafe inferred project name never escapes profile root',async()=>{const f=await fixture();const r=JSON.parse(await fsp.readFile(f.manifest));r.project.name='../escape';await write(f.manifest,r);await assert.rejects(startRestoreFromManifest({manifestPath:f.manifest,stateRoot:f.state,localProfile:{schema:'workspace-recover/profile/v3',workspaceRoot:path.join(f.d,'work')}}),/project name/);assert.equal(await fsp.stat(path.join(f.d,'escape')).catch(()=>null),null);});
test('032: missing target produces complete fillable batch and continues same session',async()=>{const f=await fixture();let s=await startRestoreFromManifest({manifestPath:f.manifest,stateRoot:f.state});assert.equal(s.state,'waiting_for_input');assert.deepEqual(s.next.required,['target']);assert.ok(s.next.valuesFile);const batch=JSON.parse(await fsp.readFile(s.next.valuesFile));assert.equal(batch.schema,'workspace-recover/values/v3');s=await continueRestore(new SessionStore(f.state),s,{target:path.join(f.d,'out')});assert.equal(s.state,'completed');});
test('032: frozen restore inputs cannot be silently replaced while waiting for auth',async()=>{const f=await fixture();const r=JSON.parse(await fsp.readFile(f.manifest));r.transport.provider={type:'google-workspace',profile:'unset'};r.transport.parts[0].remote={id:'fileID',parent:'folderID'};await write(f.manifest,r);const s=await startRestoreFromManifest({manifestPath:f.manifest,stateRoot:f.state,target:path.join(f.d,'out'),googleProfile:'missing-032-profile'});assert.equal(s.state,'waiting_for_auth');await assert.rejects(continueRestore(new SessionStore(f.state),s,{target:path.join(f.d,'other')}),/frozen/);});
test('032: Google locators reject wrong hosts and non-API message ids',()=>{assert.equal(driveId('https://drive.google.com/drive/folders/a_B-123'),'a_B-123');assert.equal(gmailMessageId('https://mail.google.com/mail/u/0/#all/1a0c71dbfb09ed40'),'1a0c71dbfb09ed40');assert.throws(()=>driveId('https://attacker.invalid/file/d/abc'),/Drive/);assert.throws(()=>gmailMessageId('https://mail.google.com/#all/opaque-ui-id'),/message ID/);});
test('032: prepared Google handoff is routed to Google before requesting auth',async()=>{const f=await fixture();const out=run(f,'restore','https://mail.google.com/mail/u/0/#all/1a0c71dbfb09ed40','--google-profile','not-authorized');assert.equal(out.status,2,out.stderr);assert.match(out.stdout,/waiting_for_auth/);assert.match(out.stdout,/Session: wr_r_/);});
test('032: restore accepts a prepared versioned values file without asking target',async()=>{const f=await fixture();const p=path.join(f.d,'restore-values.json');await write(p,{schema:'workspace-recover/values/v3',values:{target:path.join(f.d,'out')}});const out=run(f,'restore',f.manifest,'--values',p,'--non-interactive');assert.equal(out.status,0,out.stderr);assert.equal(await fsp.readFile(path.join(f.d,'out/data'),'utf8'),'preserved');});
test('032: restore never silently ignores a misspelled batch input',async()=>{const f=await fixture();const p=path.join(f.d,'restore-values.json');await write(p,{schema:'workspace-recover/values/v3',values:{targte:path.join(f.d,'out')}});const out=run(f,'restore',f.manifest,'--values',p);assert.equal(out.status,1);assert.match(out.stderr,/unknown restore input/);});
test('032: profile create never overwrites a stored local profile',async()=>{const f=await fixture();const p=path.join(f.d,'values.json');await write(p,{schema:'workspace-recover/values/v3',values:{workspaceRoot:path.join(f.d,'work')}});assert.equal(run(f,'profile','create','personal','--values',p).status,0);const first=await fsp.readFile(path.join(f.config,'profiles/personal.json'));assert.notEqual(run(f,'profile','create','personal','--values',p).status,0);assert.deepEqual(await fsp.readFile(path.join(f.config,'profiles/personal.json')),first);});
test('032: generator rejects an older template version instead of reissuing it',async()=>{const {initializeTemplate}=await import('../src/core/template.mjs');const f=await fixture();const p=path.join(f.d,'preset');await fsp.mkdir(p);await write(path.join(p,'template.json'),{schema:'workspace-recover/template/v1',name:'old',inputs:{},manifest:{}});await assert.rejects(initializeTemplate({presetDirectory:p,outputDirectory:path.join(f.d,'generated'),name:'new'}),/schema/);});
