import test from 'node:test';
import assert from 'node:assert/strict';
import fsp from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {createTarGz,extractTarGz} from '../src/core/archive.mjs';
import {startBackupFromManifest} from '../src/core/backup.mjs';
import {startRestoreFromManifest} from '../src/core/restore.mjs';
import {readJson,sha256File} from '../src/core/util.mjs';
async function fixture(t){const root=await fsp.mkdtemp(path.join(os.tmpdir(),'wr-selection-'));t.after(()=>fsp.rm(root,{recursive:true,force:true}));const source=path.join(root,'source');await fsp.mkdir(source);for(const name of ['root.log','nest/child.log','nest/keep.txt','deep/a/data.txt','.env','.git/HEAD','.gitignore','root.LOG','a','nested/b','line\nbreak.txt']){await fsp.mkdir(path.dirname(path.join(source,name)),{recursive:true});await fsp.writeFile(path.join(source,name),name);}await fsp.mkdir(path.join(source,'empty'));return {root,source,output:path.join(root,'a.tar.gz'),destination:path.join(root,'out')};}
async function names(f,opts){const a=await createTarGz({...f,...opts});return {a,names:a.entries};}
test('035: globstar matches zero or more levels and preserves case',async t=>{const f=await fixture(t);const r=await names(f,{excludes:['**/*.log']});assert.ok(!r.names.includes('root.log'));assert.ok(!r.names.includes('nest/child.log'));assert.ok(r.names.includes('root.LOG'));});
test('035: selective leaf include adds parents without adding excluded siblings',async t=>{const f=await fixture(t);const r=await names(f,{includes:['deep/a/data.txt','nest/keep.txt'],excludes:['nest/child.log']});assert.deepEqual(r.names,['./','deep/','deep/a/','deep/a/data.txt','nest/','nest/keep.txt']);});
test('035: dotfiles and gitignore are not silently filtered',async t=>{const f=await fixture(t);await fsp.writeFile(path.join(f.source,'.gitignore'),'.env\n');const r=await names(f,{includes:['.git/','.env'],excludes:[]});assert.deepEqual(r.names,['./','.env','.git/','.git/HEAD']);});
test('035: exclude a directory removes its subtree regardless of include',async t=>{const f=await fixture(t);const r=await names(f,{includes:['**'],excludes:['nest/']});assert.ok(!r.names.some(x=>x.startsWith('nest/')));assert.ok(r.names.includes('empty/'));});
test('035: question mark never crosses a separator; zero-match include is explicit empty root',async t=>{const f=await fixture(t);const r=await names(f,{includes:['?'],excludes:[]});assert.deepEqual(r.names,['./','a']);});
test('035: empty include yields only root metadata, not default all',async t=>{const f=await fixture(t);const r=await names(f,{includes:[]});assert.deepEqual(r.names,['./']);});
test('035: invalid path patterns are rejected before creating an archive',async t=>{const f=await fixture(t);await assert.rejects(()=>names(f,{includes:['../outside']}),/pattern|relative|source/i);await assert.rejects(()=>names(f,{excludes:'*.log'}),/array|patterns/i);assert.equal(await fsp.stat(f.output).catch(()=>null),null);});
test('035: an included symlink is one record, never a recursive walk',async t=>{const f=await fixture(t);await fsp.symlink('nest',path.join(f.source,'alias'));const r=await names(f,{includes:['alias']});assert.deepEqual(r.names,['./','alias']);assert.equal(r.a.inventory.entries.find(e=>e.path==='alias').target,'nest');});
test('035: capture inventory includes content hashes and exact NUL-safe filenames',async t=>{const f=await fixture(t);const r=await names(f,{includes:['line\nbreak.txt']});assert.equal(r.a.inventory.schema,'workspace-recover/selection/v3');const e=r.a.inventory.entries.find(e=>e.path==='line\nbreak.txt');assert.equal(e.sha256,await sha256File(path.join(f.source,e.path)));assert.equal(e.type,'file');await extractTarGz({archive:f.output,destination:f.destination,inventory:r.a.inventory});assert.equal(await fsp.readFile(path.join(f.destination,e.path),'utf8'),e.path);});
test('035: mismatched inventory fails before author workflow and cannot claim success',async t=>{const f=await fixture(t);const r=await names(f,{includes:['.env']});const inventory=structuredClone(r.a.inventory);inventory.entries.find(e=>e.type==='file').sha256='f'.repeat(64);await assert.rejects(()=>extractTarGz({archive:f.output,destination:f.destination,inventory}),/inventory|hash|checksum/i);});
test('035: public backup publishes selection and restore validates it before tests',async t=>{const f=await fixture(t),remote=path.join(f.root,'remote'),marker=path.join(f.root,'marker');const m={schema:'workspace-recover/manifest/v3',backup:{source:{path:f.source,include:['nest/keep.txt'],exclude:[]},provider:{type:'local-files',root:remote}},restore:{workflow:[{id:'observed',type:'verification',argv:[process.execPath,'-e',`require('fs').appendFileSync(${JSON.stringify(marker)},'once\\n')`]}]},handoff:{provider:{type:'local-files',root:remote},subject:'rebranding'}};const file=path.join(f.root,'m.json');await fsp.writeFile(file,JSON.stringify(m));const s=await startBackupFromManifest({manifestPath:file,stateRoot:path.join(f.root,'state')});assert.equal(s.state,'completed',JSON.stringify(s));assert.ok(s.info.selection);const b=path.dirname(s.planPath),recovery=await readJson(path.join(b,'workspace-recovery-manifest.json'));assert.ok(recovery.selection?.sha256);const dir=path.join(f.root,'restored');const restored=await startRestoreFromManifest({manifestPath:path.join(b,'workspace-recovery-manifest.json'),target:dir,stateRoot:path.join(f.root,'rstate')});assert.equal(restored.state,'completed');assert.equal(await fsp.stat(path.join(dir,'root.log')).catch(()=>null),null);assert.equal(await fsp.readFile(path.join(dir,'nest/keep.txt'),'utf8'),'nest/keep.txt');});
test('035: malformed inventory schemas, duplicates and unsafe paths cannot bypass checking',async t=>{const f=await fixture(t),r=await names(f,{includes:['.env']});for(const mutate of [x=>x.schema='workspace-recover/selection/v2',x=>x.entries.push({...x.entries[0]}),x=>x.entries[1].path='../outside',x=>x.entries[1].mode=-1]){const inv=structuredClone(r.a.inventory);mutate(inv);await assert.rejects(()=>extractTarGz({archive:f.output,destination:path.join(f.root,Math.random().toString(16).slice(2)),inventory:inv}));}});
test('035: required missing selection is rejected before provider invocation',async()=>{const {executeRecoveryManifest}=await import('../src/core/restore.mjs');let calls=0;const recovery={schema:'workspace-recover/recovery-manifest/v3',requires:{formatVersion:3,features:['selection-inventory']},transport:{schema:'workspace-recover/transport-manifest/v3',archive:{fileName:'a.tar.gz',format:'tar.gz',bytes:1,sha256:'a'.repeat(64)},parts:[{index:0,fileName:'part',bytes:1,sha256:'a'.repeat(64),remote:{id:'x'}}]},restore:{workflow:[]}};await assert.rejects(()=>executeRecoveryManifest({recovery,target:'/unused',sessionDir:'/unused',provider:{download(){calls++;}}}),/selection/);assert.equal(calls,0);});
test('035: selected-files NUL representation preserves newline, leading dash, and unicode',async t=>{const {selectSource,selectionNul}=await import('../src/core/selection.mjs');const f=await fixture(t);await fsp.writeFile(path.join(f.source,'--option'),'safe');await fsp.writeFile(path.join(f.source,'данные'),'safe');const selection=await selectSource({source:f.source,includes:['line\nbreak.txt','--option','данные']});assert.deepEqual(selectionNul(selection).toString().split('\0'),['.','--option','line\nbreak.txt','данные','']);});

test('035: published required-format JSON schema matches the current runtime version',async()=>{const {FORMAT_VERSION}=await import('../src/core/formats.mjs');const document=JSON.parse(await fsp.readFile(new URL('../schemas/requirements.schema.json',import.meta.url)));assert.equal(document.properties.formatVersion.const,FORMAT_VERSION);});
